# Generated by Django 3.2.5 on 2022-01-29 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cCategoria', models.CharField(default='', max_length=360, verbose_name='Categoria')),
                ('lVigente', models.BooleanField(default=True, verbose_name='Vigente')),
            ],
            options={
                'verbose_name_plural': '1. Categorias',
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cGrupo', models.CharField(default='', max_length=360, verbose_name='Grupo')),
                ('lVigente', models.BooleanField(default=True, verbose_name='Vigente')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='evidencia.categoria')),
            ],
            options={
                'verbose_name_plural': '2. Grupos',
            },
        ),
        migrations.CreateModel(
            name='Indicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cTitulo', models.CharField(default='', max_length=120, verbose_name='Titulo')),
                ('cIndicador', models.CharField(default='', max_length=360, verbose_name='Indicador')),
                ('cDescripcion', models.CharField(default='', max_length=360, verbose_name='Descripción')),
                ('nOrden', models.IntegerField(default=0, verbose_name='Orden')),
                ('lVigente', models.BooleanField(default=True, verbose_name='Vigente')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='evidencia.grupo')),
            ],
            options={
                'verbose_name_plural': '3. Indicadores',
            },
        ),
        migrations.CreateModel(
            name='MedioVerificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cTitulo', models.CharField(default='', max_length=120, verbose_name='Titulo')),
                ('cMedioVerificacion', models.CharField(max_length=360, verbose_name='Medio de Verificación')),
                ('nOrden', models.IntegerField(default=0, verbose_name='Orden')),
                ('dFechaMaxEntrega', models.DateField(blank=True, null=True, verbose_name='Fecha Max Entrega')),
                ('lVigente', models.BooleanField(default=True, verbose_name='Vigente')),
                ('indicador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='evidencia.indicador')),
                ('oficinaResponsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='usuario.oficina')),
            ],
            options={
                'verbose_name_plural': '4. Medios de Verficación',
            },
        ),
        migrations.CreateModel(
            name='Evidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idEstado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Cargado', 'Cargado'), ('Revisado', 'Revisado'), ('Observado', 'Observado'), ('Aprobado', 'Aprobado')], default='Pendiente', max_length=20, verbose_name='Estado')),
                ('idEscala', models.CharField(choices=[('Contextualizacion', 'Contextualización'), ('Planificacion', 'Planificación'), ('Optimizacion', 'Optimización'), ('Avance de actividades al 25%', 'Avance de actividades al 25%'), ('Avance de actividades al 50%', 'Avance de actividades al 50%'), ('Avance de actividades al 75%', 'Avance de actividades al 75%'), ('Avance de actividades al 100%', 'Avance de actividades al 100%'), ('Análisis de resultados', 'Análisis de resultados'), ('Justificacion', 'Justificación')], default='Contextualizacion', max_length=120, verbose_name='Escala')),
                ('cDetalle1', models.CharField(blank=True, default='', max_length=480, null=True, verbose_name='Primer Detalle')),
                ('cDetalle2', models.CharField(blank=True, default='', max_length=480, null=True, verbose_name='Segundo Detalle')),
                ('archivoPdf', models.FileField(blank=True, default='', null=True, upload_to='pdf/')),
                ('dFechaCarga', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Carga')),
                ('lRevisado', models.BooleanField(default=False, verbose_name='Revisado')),
                ('cComentarioRevisor', models.CharField(blank=True, max_length=360, null=True, verbose_name='Comentario de Revisor')),
                ('dFechaRevision', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Revisión')),
                ('medioVerificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medio_verificado', to='evidencia.medioverificacion')),
                ('oficina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oficina', to='usuario.oficina')),
                ('usuarioCarga', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidencia_cargada', to=settings.AUTH_USER_MODEL)),
                ('usuarioRevisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidencia_revisada', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '5. Evidencias',
            },
        ),
    ]
