# Generated by Django 3.2.5 on 2021-11-30 15:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cCategoria', models.CharField(default='', max_length=360, verbose_name='Categoria')),
                ('lVigente', models.BooleanField(default=True, verbose_name='Vigente')),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cGrupo', models.CharField(default='', max_length=360, verbose_name='Grupo')),
                ('lVigente', models.BooleanField(default=True, verbose_name='Vigente')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='evidencia.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Indicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cIndicador', models.CharField(default='', max_length=360, verbose_name='Indicador')),
                ('cDescripcion', models.CharField(default='', max_length=360, verbose_name='Descripción')),
                ('nOrden', models.IntegerField(default=0, verbose_name='Orden')),
                ('lVigente', models.BooleanField(default=True, verbose_name='Vigente')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='evidencia.grupo')),
            ],
        ),
        migrations.CreateModel(
            name='MedioVerificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cMedioVerificacion', models.CharField(max_length=360, verbose_name='Medio de Verificación')),
                ('cDescripcion', models.CharField(max_length=360, verbose_name='Descripción')),
                ('lVigente', models.BooleanField(default=True, verbose_name='Vigente')),
                ('nOrden', models.IntegerField(default=0, verbose_name='Orden')),
                ('dFechaMaxEntrega', models.DateField(blank=True, null=True, verbose_name='Fecha Max Entrega')),
                ('idEstado', models.IntegerField(blank=True, null=True, verbose_name='Estado')),
                ('archivoPdf', models.FileField(blank=True, default='', null=True, upload_to='pdf/')),
                ('dFechaCarga', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Carga')),
                ('lRevisado', models.BooleanField(default=False, verbose_name='Revisado')),
                ('cComentarioRevisor', models.CharField(blank=True, max_length=360, null=True, verbose_name='Comentario de Revisor')),
                ('dFechaRevision', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Revisión')),
                ('indicador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='evidencia.indicador')),
                ('oficinaResponsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='usuario.oficina')),
                ('usuarioCarga', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidencia_cargada', to=settings.AUTH_USER_MODEL)),
                ('usuarioRevisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidencia_revisada', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
