# Generated by Django 3.2.5 on 2021-11-30 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidencia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medioverificacion',
            name='idEstado',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Estado'),
        ),
    ]
