# Generated by Django 3.2.5 on 2021-11-30 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evidencia', '0002_alter_medioverificacion_idestado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medioverificacion',
            name='cDescripcion',
        ),
    ]
