# Generated by Django 3.2.5 on 2022-05-14 01:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('evidencia', '0003_auto_20220513_2018'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evidencia_Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idEstado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Cargado', 'Cargado'), ('Revisado', 'Revisado'), ('Observado', 'Observado'), ('Aprobado', 'Aprobado')], default='Pendiente', max_length=20, verbose_name='Estado')),
                ('idEscala', models.CharField(choices=[('1', 'Contextualización'), ('2', 'Planificación'), ('3', 'Optimización'), ('3', 'Avance de actividades al 25%'), ('4', 'Avance de actividades al 50%'), ('5', 'Avance de actividades al 75%'), ('6', 'Avance de actividades al 100%'), ('7', 'Análisis de resultados'), ('8', 'Justificación'), ('9', 'Finalizado')], default='Contextualizacion', max_length=120, verbose_name='Escala')),
                ('cDetalle1', models.TextField(blank=True, default='', null=True, verbose_name='Primer Detalle')),
                ('cDetalle2', models.TextField(blank=True, default='', null=True, verbose_name='Segundo Detalle')),
                ('archivoPdf', models.FileField(blank=True, default='', null=True, upload_to='pdf/')),
                ('dFechaCarga', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Carga')),
                ('lRevisado', models.BooleanField(default=False, verbose_name='Revisado')),
                ('cComentarioRevisor', models.CharField(blank=True, max_length=360, null=True, verbose_name='Comentario de Revisor')),
                ('dFechaRevision', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Revisión')),
                ('medioVerificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='evidencia.medioverificacion')),
                ('oficina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oficinas', to='usuario.oficina')),
                ('usuarioCarga', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidencia_cargado', to=settings.AUTH_USER_MODEL)),
                ('usuarioRevisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidencia_revisado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '6. Evidencias Todo',
            },
        ),
    ]
