# Generated by Django 3.2.5 on 2022-05-22 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidencia', '0005_auto_20220517_0704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidencia',
            name='idEscala',
            field=models.CharField(choices=[('1', 'Contextualización'), ('2', 'Planificación'), ('3', 'Optimización'), ('4', 'Avance de actividades al 25%'), ('5', 'Avance de actividades al 50%'), ('6', 'Avance de actividades al 75%'), ('7', 'Avance de actividades al 100%'), ('8', 'Análisis de resultados'), ('9', 'Justificación'), ('10', 'Finalizado')], default='1', max_length=120, verbose_name='Escala'),
        ),
    ]
