# Generated by Django 3.2.5 on 2023-10-23 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidencia', '0006_alter_evidencia_idescala'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medioverificacion',
            name='cMedioVerificacion',
            field=models.CharField(max_length=700, verbose_name='Medio de Verificación'),
        ),
        migrations.AlterField(
            model_name='medioverificacion',
            name='cTitulo',
            field=models.CharField(default='', max_length=500, verbose_name='Titulo'),
        ),
    ]
