# Generated by Django 3.2.5 on 2024-06-10 02:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('evidencia', '0007_auto_20231023_0810'),
    ]

    operations = [
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cPeriodo', models.CharField(default='', max_length=360, verbose_name='Periodo')),
                ('lVigente', models.BooleanField(default=True, verbose_name='Vigente')),
            ],
            options={
                'verbose_name_plural': '7. Periodos',
            },
        ),
        migrations.RemoveField(
            model_name='evidencia',
            name='archivoPdf',
        ),
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idEscala', models.CharField(choices=[('1', 'Contextualización'), ('2', 'Planificación'), ('3', 'Optimización'), ('4', 'Avance de actividades al 25%'), ('5', 'Avance de actividades al 50%'), ('6', 'Avance de actividades al 75%'), ('7', 'Avance de actividades al 100%'), ('8', 'Análisis de resultados'), ('9', 'Justificación'), ('10', 'Finalizado')], default='Contextualizacion', max_length=120, verbose_name='Escala')),
                ('archivoPdf', models.FileField(blank=True, default='', null=True, upload_to='pdf/')),
                ('dFecha', models.DateTimeField(blank=True, null=True, verbose_name='Cargado')),
                ('dFechaMod', models.DateTimeField(blank=True, null=True, verbose_name='Modificado')),
                ('lVigente', models.BooleanField(default=True, verbose_name='Vigente')),
                ('evidencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='evidencia.evidencia')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidencia_carga', to=settings.AUTH_USER_MODEL)),
                ('usuarioMod', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidencia_actualiza', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '8. Archivos',
            },
        ),
        migrations.AddField(
            model_name='evidencia',
            name='periodo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='evidencia.periodo'),
        ),
        migrations.AddField(
            model_name='evidencia_todo',
            name='periodo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='evidencia.periodo'),
        ),
    ]
