# Generated by Django 3.2.5 on 2024-06-10 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evidencia', '0008_auto_20240609_2138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evidencia_todo',
            name='archivoPdf',
        ),
    ]
