# Generated by Django 3.2.5 on 2024-06-12 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evidencia', '0009_remove_evidencia_todo_archivopdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodo',
            name='grupo',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='evidencia.grupo'),
        ),
    ]
