# Generated by Django 3.2.5 on 2024-06-18 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evidencia', '0010_periodo_grupo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='periodo',
            name='grupo',
        ),
        migrations.AddField(
            model_name='periodo',
            name='categoria',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='evidencia.categoria'),
        ),
    ]
