# Generated by Django 3.2.5 on 2024-08-10 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidencia', '0012_auto_20240723_0757'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidencia',
            name='lFinalizado',
            field=models.BooleanField(default=False, null=True, verbose_name='Finalizado'),
        ),
    ]
