# Generated by Django 3.2.5 on 2024-08-20 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidencia', '0013_evidencia_lfinalizado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivo',
            name='idEscala',
            field=models.CharField(choices=[('1', 'Contextualización'), ('2', 'Planificación'), ('3', 'Optimización'), ('4', 'Avance al 25%'), ('5', 'Avance al 50%'), ('6', 'Avance al 75%'), ('7', 'Avance al 100%'), ('8', 'Análisis de resultados'), ('9', 'Justificación'), ('10', 'Finalizado')], default='Contextualizacion', max_length=120, verbose_name='Escala'),
        ),
        migrations.AlterField(
            model_name='evidencia',
            name='idEscala',
            field=models.CharField(choices=[('1', 'Contextualización'), ('2', 'Planificación'), ('3', 'Optimización'), ('4', 'Avance al 25%'), ('5', 'Avance al 50%'), ('6', 'Avance al 75%'), ('7', 'Avance al 100%'), ('8', 'Análisis de resultados'), ('9', 'Justificación'), ('10', 'Finalizado')], default='1', max_length=120, verbose_name='Escala'),
        ),
        migrations.AlterField(
            model_name='evidencia_todo',
            name='idEscala',
            field=models.CharField(choices=[('1', 'Contextualización'), ('2', 'Planificación'), ('3', 'Optimización'), ('4', 'Avance al 25%'), ('5', 'Avance al 50%'), ('6', 'Avance al 75%'), ('7', 'Avance al 100%'), ('8', 'Análisis de resultados'), ('9', 'Justificación'), ('10', 'Finalizado')], default='Contextualizacion', max_length=120, verbose_name='Escala'),
        ),
    ]
