# Generated by Django 3.2.5 on 2024-08-20 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidencia', '0014_auto_20240820_0644'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodo',
            name='lFinalizado',
            field=models.BooleanField(default=False, verbose_name='Finalizado'),
        ),
    ]
