# Generated by Django 3.2.5 on 2024-08-30 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evidencia', '0015_periodo_lfinalizado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archivo',
            options={'verbose_name_plural': '6. Archivos'},
        ),
        migrations.AlterModelOptions(
            name='revision',
            options={'verbose_name_plural': '7. Revisiones'},
        ),
        migrations.RemoveField(
            model_name='indicador',
            name='cDescripcion',
        ),
        migrations.RemoveField(
            model_name='indicador',
            name='cTitulo',
        ),
        migrations.RemoveField(
            model_name='medioverificacion',
            name='cTitulo',
        ),
    ]
