# Generated by Django 3.2.5 on 2024-08-30 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evidencia', '0016_auto_20240829_2104'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='periodo',
            options={'verbose_name_plural': '8. Periodos'},
        ),
    ]
